### ISSUE TITLE
Neighbors' Radius vs Attention Radius

### ISSUE THREAD

**Issue by m43** [amazon-science/explainable-trajectory-prediction#11]
Hi Osama,

Thanks for the nice work!

I was wondering why you had separated the neighbors' radius from the attention radius. The two are, for example, defined [here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/models/trajectron/sport/orig/config.json). For what I could dig out, the neighbors' radius is used to compute the scene graph [here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/src/explainable_trajectory_prediction/trajectron/train.py#L128), and the attention radius is used to overwrite the position standardization parameters [here](https://github.com/m43/explainable-trajectory-prediction/blob/add-direct-regularization/src/explainable_trajectory_prediction/trajectron/dataset.py#L104) and again [here](https://github.com/m43/explainable-trajectory-prediction/blob/add-direct-regularization/src/explainable_trajectory_prediction/trajectron/dataset.py#L194) when recomputing the scene graph.

Should the two parameters be separated?
Would you remember why you had separated them?
Would you know how to configure the radii when adapting the model for a new dataset?

Best,
Frano

**Comment by os1a** [comment]
Hi Frano,

Thanks for reaching out regarding our paper.

As for the two parameters, the neighbors radius control how many neighbors are needed to compute the scene graph (as you found out). In the Sport-VU dataset, this corresponds to all players. However, in the original Trajectron++, they used smaller values (to compute the grapy only for a sub-set of neighbors for crowdy environments).

The other parameter controls the distance to the neighbors to be considered when computing the scene graph. So this can be seen as a way of controlling the number of neighbors (the closer to be used). These two parameters come from the original Trajectron++ and we used them as such. More information can be found here: https://github.com/StanfordASL/Trajectron-plus-plus/blob/ef0165a93ee5ba8cdc14f9b999b3e00070cd8588/trajectron/environment/scene_graph.py#L166

Best,
Osama

**Comment by os1a** [comment]
I am closing this, please feel free to reopen it if you have more questions.
