### ISSUE TITLE
Biased Shapley Value Implementation

### ISSUE THREAD

**Issue by m43** [amazon-science/explainable-trajectory-prediction#9]
Thanks for the nice work!

The Shapley values implementation gives a biased estimate of the formula given in the paper as the weighting factor is missing. This leads to biased Shapley value estimates, though I do not believe it would change the gist of your results.

Some relevant pointers to how Shapley values are currently computed in the codebase:
1. The Shapley value `(positive,negative)` pairs are prepared [here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/src/explainable_trajectory_prediction/trajectron/shapley_values.py#L79-L89) for example for the neighbors.
2. Since each feature is dropped/replaced with a 50% chance ([here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/src/explainable_trajectory_prediction/trajectron/shapley_values.py#L84-L85) and [here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/src/explainable_trajectory_prediction/trajectron/network.py#L146)), there is an equal probability for each coalition size (i.e., feature subset size), `|S|`.
3. The Shapley value is then computed as the average of those pairs [here](https://github.com/amazon-science/explainable-trajectory-prediction/blob/main/src/explainable_trajectory_prediction/trajectron/shapley_values.py#L210-L212).

My back-of-the-envelope expectation computation suggests that in such case a weighting factor of $\frac{2^{n-1}}{n {n - 1 \choose |S|}}$ needs to be added to unbias the estimate of the Shapley value, where n is the number of features for the current datapoint (i.e., the history and visible neighbors) and $|S|$ is the number of features (history/neighbors) that will be dropped/replaced. The numerator is needed to take into account the sampling probability of each sample, as each of the n-1 features will be dropped/replaced with a probability of $\frac{1}{2}$.

Do you possibly have some insights on the missing weighting factor? Was the weighting factor left out on purpose?

**Comment by os1a** [comment]
Hi,

Thanks for your question and interest in our paper.

Yes, you are right, but in our experimental results, we observe no difference between adding the weights or not, hence we opt for the simpler version in the code.

Best,
Osama

**Comment by m43** [comment]
Thank you for the quick response and clarification, Osama. Closing the issue in that case!
